// <auto-generated />
namespace XLibrary.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddReservation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddReservation));
        
        string IMigrationMetadata.Id
        {
            get { return "202110071824216_AddReservation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
